language: java
jdk:
  - openjdk8

# Git Push할 Branch
branches:
  only:
    - travis-deploy

# gradlew 권한 추가
before_install:
  - chmod +x gradlew

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r team8-deploy *
  - mkdir -p deploy
  - mv team8-deploy.zip deploy/team8-deploy.zip

# 배포 설정값
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis-ci 웹 repo settings에서 설정해줘야 함.
    secret_access_key: $AWS_SECRET_KEY # Travis-ci 웹 repo settings에서 설정해줘야 함.
    bucket: team8-deploy # 생성한 S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: public_read
    wait-until-deployed: true
    on:
      repo: Team8-Project/back #Github 주소
      branch: travis-deploy
    local_dir: deploy # before_deploy에서 생성한 디렉토리

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: team8-deploy # S3 버킷
    key: team8-deploy.zip # S3 버킷에 저장된 team8-deploy.zip 파일을 EC2로 배포
    bundle_type: zip
    application: memeglememegle-deploy # 웹 콘솔에서 등록한 CodeDeploy 어플리케이션
    deployment_group: memeglememegle-deploy-group # 웹 콘솔에서 등록한 CodeDeploy 배포 그룹
    region: ap-northeast-2
    wait-until-deployed: true
    on:
      repo: Team8-Project/back
      branch: travis-deploy

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - zabeee52@gmail.com