language: java
jdk:
  - openjdk8

# Git Push할 Branch
branches:
  only:
    - travis-test

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - zabeee52@gmail.com